var OVERWORLD = [
  ["       cb123db    cb121212123db    cb123db       ",
   "       cb456dbxxxxcb454545456dbxxxxcb456db       ",
   "       aaaaaaa    cb121212123db    aaaaaaa       ",
   "                  cb454545456db                  ",
   "                  aaaaaaaaaaaaa                  ",
   "                                                 ",
   "                        h  h                     ",
   "   qs            qs    gnigni    qs              ",
   "                h  h  gmfoptors          qs      ",
   "     h         gnignigmklwvuwoi  h         h     ",
   "    gnrs  @   gmfoptjmkkfwwwwwvigni   $   gni    ",
   "   gmfvi aaa gmklwvjkkkklwwwwwwoptoi aaa gmfoi   ",
   "  gmklwoi x gmkkfwjkkkkkfwwwwwwwvuwvi x gmklwvi  ",
   " gmkkfwaaaaaaakkljkkkkkklwwwwwwwwouaaaaaaakfwwoi ",
   "gmkkklwcb123dbkkekkkkkkkfwwwwwwwwwvcb123dbklwwwvi",
   "mkkkkfwcb456dbkkkkaaaaaaaaaaaaawwwwcb456dbkfwwwwo",
   "kkkkklwcb123dbkkkkcb121212123dbwwwwcb123dbklwwwww",
   "kkkkkfwcb456dbkkkkcb454545456dbwwwwcb456dbkfwwwww",
   "kkkkkljcb123db!!!!cb121212123db||||cb123dbklwwwww"]
];